var o=document.getElementById("but_sear");if(o!=null){o.onclick=null;s='';s+='<a class="mi n3" onclick="loadjs(\'adv_search\');" id="but_adv">'+$w142+'</a>';if($qua)s+='<a class="mi n3 otb" onclick="loadjs(\'adv_search2\');" id="but_adv2">'+$w143+'</a>';else s+='<span class="otb"></span><a class="mi n3" onclick="loadjs(\'adv_search2\');" id="but_adv2">'+$w144+'</a>';s+='<br /><select name="тип" id="тип" class="opm"><option>'+$w123+'</option>';for($i=0;$i<$ref_t.length;$i++){s+='<option';if($ref_t[$i]==$ctip)s+=' selected';s+='>'+$ref_t[$i]+'</option>';}
s+='</select><select name=язык id=язык class="opm"><option>'+$w11+'</option>';for($i=0;$i<$langs.length;$i++){s+='<option';if($langs[$i]==$clang)s+=' selected';s+='>'+$langs[$i]+'</option>';}
s+='</select><select name=категория id=категория style="width:300px"><option>'+$w122+'</option></select>';if($sokr==1)s+='<input type="hidden" name="сокр" value="1" />';s+='<br /><input class="searB" value="'+$v+'" size="55" name="поиск" id="Search1" type="text" autocomplete="off" maxlength="128" />';s+='<br><input type="submit" width="50" title="'+$w125+'" value="'+$w137+'" />'
s+='<p id="res_list" style="margin:0px;background-color:#CCCCCC;"></p>';o.innerHTML=s;obj=document.getElementById('категория');obj2=document.getElementById('категория2');s='';var a=Array('Астрономия','География','Биология','БЖД','История','Иностранные языки','Информатика','Культура','Литература','Математика','Физика','Философия','Химия','Банк','Геология','Государство и право','Военное дело','Бухгалтерия','Журналистика','Коммуникации','Логика','Медицина','Педагогика','Психология','Религия','Спорт','Сексология','Таможня','Экономика','Экология','Этика');var i=0;while(a[i]!=null){s+='<option';if(tek_kat==a[i]){s+=' selected';}
s+='>'+a[i]+'</option>';i+=1;}
if(obj)obj.innerHTML+=s;if(obj2!=null)obj2.innerHTML=s;if(window.ActiveXObject){var o5=document.getElementById("form2");if(o5!=null)o5.innerHTML=o5.innerHTML;}
$o=document.getElementById('Search1');if($o!=null)old_s2=$o.value;if(old_s2==''){var o2=document.getElementById('Search2');if(o2!=null)old_s2=o2.value;}
if(($o!=null)&&($o.value=='')){$o.focus();}
function sdf(){$o.style.background='#FFFFFF';if(thb==1){thb=0;$o.value='';}}
function sdb(){if($o.value=='')$o.style.background='#FFFFFF url(http://coolreferat.com/images/logos.png) left no-repeat';}
if($o!=null){$o.onfocus=sdf;$o.onblur=sdb;$o.onchange=ch0;$o.onkeyup=up0;}}